package store

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/google/uuid"

	"github.com/scottlaird/roz/internal/markdown"
)

// timeFormat is ISO-8601 UTC at millisecond precision: sorts correctly as
// text and stays readable in a sqlite3 shell.
const timeFormat = "2006-01-02T15:04:05.000Z"

// TimeFormat is timeFormat, for callers that have to compare against the same
// instant the queries do. A snooze until a bare date is past the moment that
// date starts, which only comes out right if both sides compare against a
// timestamp: "2026-08-12" sorts before "2026-08-12T00:00:00.000Z", and after
// "2026-08-12" alone it does not.
const TimeFormat = timeFormat

// Store is a handle on an initialised database.
//
// It reads the identifier prefixes once, at construction, so commands never
// have to be told them.
type Store struct {
	db       *sql.DB
	prefixes map[Entity]string

	// now is swappable so tests can pin timestamps.
	now func() time.Time
}

// New wraps an open database. The database must already be initialised; use
// Init for that.
func New(db *sql.DB) (*Store, error) {
	prefixes, err := LoadPrefixes(db)
	if err != nil {
		return nil, err
	}
	return &Store{db: db, prefixes: prefixes, now: time.Now}, nil
}

// Prefix returns the identifier prefix configured for an entity.
func (s *Store) Prefix(entity Entity) string { return s.prefixes[entity] }

// Tx is a unit of work.
//
// Every change made through one Tx shares a correlation id, so a cascade —
// closing one action unblocking a second and closing a third — is
// recoverable from the log as a single command rather than three unrelated
// events. All its events also share one timestamp; event.seq is the tiebreak
// that recovers their order, since millisecond stamps collide inside a
// cascade.
//
// The caller must call Commit or Rollback.
type Tx struct {
	tx          *sql.Tx
	actor       Actor
	correlation string
	at          string
}

// Begin starts a unit of work attributed to actor.
func (s *Store) Begin(ctx context.Context, actor Actor) (*Tx, error) {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return nil, fmt.Errorf("beginning transaction: %w", err)
	}
	return &Tx{
		tx:          tx,
		actor:       actor,
		correlation: uuid.NewString(),
		at:          s.now().UTC().Format(timeFormat),
	}, nil
}

// Commit makes the unit of work permanent.
func (t *Tx) Commit() error {
	if err := t.tx.Commit(); err != nil {
		return fmt.Errorf("committing transaction: %w", err)
	}
	return nil
}

// Rollback discards the unit of work. It is safe to call after Commit, so it
// works as a deferred cleanup.
func (t *Tx) Rollback() error {
	err := t.tx.Rollback()
	if err == nil || err == sql.ErrTxDone {
		return nil
	}
	return fmt.Errorf("rolling back transaction: %w", err)
}

// Correlation is the id shared by every event this unit of work writes.
func (t *Tx) Correlation() string { return t.correlation }

// Load reads the record with the given id into r.
//
// It returns sql.ErrNoRows if there is no such row, so callers can use
// errors.Is to tell "missing" from "broken".
func (t *Tx) Load(ctx context.Context, r Record, id string) error {
	fields, err := fieldsOf(r)
	if err != nil {
		return err
	}

	columns := make([]string, len(fields))
	dest := make([]any, len(fields))
	for i, f := range fields {
		columns[i] = f.column
		dest[i] = f.pointer(r)
	}

	// Table and column names come from struct tags, not from user input.
	query := fmt.Sprintf("SELECT %s FROM %s WHERE %s = ?",
		strings.Join(columns, ", "), r.table(), keyColumnOf(r))
	if err := t.tx.QueryRowContext(ctx, query, id).Scan(dest...); err != nil {
		return err
	}
	return nil
}

// Insert writes a new record and logs a created event.
//
// The caller is responsible for having allocated the record's identifier with
// Store.Allocate first, and for setting its authored fields; Insert fills in
// the auto ones.
func (t *Tx) Insert(ctx context.Context, r Record) error {
	fields, err := fieldsOf(r)
	if err != nil {
		return err
	}
	if err := t.checkInsertPermission(r, fields); err != nil {
		return err
	}
	if err := checkProse(r, fields, nil); err != nil {
		return err
	}
	t.stampNew(r, fields)

	var columns []string
	var placeholders []string
	var args []any
	for _, f := range fields {
		if f.kind == Derived {
			continue // generated by the database; not writable
		}
		columns = append(columns, f.column)
		placeholders = append(placeholders, "?")
		args = append(args, f.value(r))
	}

	query := fmt.Sprintf("INSERT INTO %s (%s) VALUES (%s)",
		r.table(), strings.Join(columns, ", "), strings.Join(placeholders, ", "))
	if _, err := t.tx.ExecContext(ctx, query, args...); err != nil {
		return fmt.Errorf("inserting %s %s: %w", r.table(), r.subjectID(), err)
	}

	return t.emit(ctx, r, event{kind: eventCreated})
}

// Update writes the difference between before and after, and logs one event
// per changed column.
//
// It returns the changes applied, which is empty when the two are identical —
// a no-op update writes nothing at all, touching neither updated_at nor the
// log.
//
// Writing a column the actor is not allowed to write is an error, not a
// silent skip: it means the caller has confused a fact with a judgement.
func (t *Tx) Update(ctx context.Context, before, after Record) ([]Change, error) {
	changes, err := diff(before, after)
	if err != nil {
		return nil, err
	}
	if len(changes) == 0 {
		return nil, nil
	}
	if err := t.checkPermission(after, changes); err != nil {
		return nil, err
	}

	fields, err := fieldsOf(after)
	if err != nil {
		return nil, err
	}
	if err := checkProse(after, fields, changedColumns(changes)); err != nil {
		return nil, err
	}
	t.stamp(after, fields, Auto)

	assignments, args := t.assignments(after, fields, changes)
	args = append(args, after.subjectID())
	query := fmt.Sprintf("UPDATE %s SET %s WHERE %s = ?",
		after.table(), strings.Join(assignments, ", "), keyColumnOf(after))
	if _, err := t.tx.ExecContext(ctx, query, args...); err != nil {
		return nil, fmt.Errorf("updating %s %s: %w", after.table(), after.subjectID(), err)
	}

	for _, change := range changes {
		err := t.emit(ctx, after, event{
			kind:     eventChanged,
			field:    change.Column,
			oldValue: change.Old,
			newValue: change.New,
		})
		if err != nil {
			return nil, err
		}
	}
	return changes, nil
}

// checkInsertPermission applies the actor rule to a new record. Update sees a
// before image and can diff; Insert has none, so the test is whether a column
// the actor may not write has been given a value at all.
func (t *Tx) checkInsertPermission(r Record, fields []field) error {
	allowed := t.actor.writes()
	for _, f := range fields {
		if f.kind != Authored && f.kind != Observed {
			continue // the store's own columns
		}
		if f.kind == allowed {
			continue
		}
		text, err := renderValue(f.value(r))
		if err != nil {
			return fmt.Errorf("%s.%s: %w", r.table(), f.column, err)
		}
		if isUnset(f, text) {
			continue // nothing was claimed
		}
		return fmt.Errorf("%s may not set %s.%s at creation: it is %s, and %s writes only %s fields",
			t.actor, r.table(), f.column, f.kind, t.actor, allowed)
	}
	return nil
}

// isUnset reports whether a column carries no information, so that having a
// value there is not a claim about anything.
//
// Empty is empty whether it is spelled "", {} or []. Without this, the empty
// containers a constructor supplies for JSON columns would read as a human
// asserting observed facts, and tracking a pull request would be refused.
func isUnset(f field, text string) bool {
	if text == "" {
		return true
	}
	return f.format == formatJSON && (text == "{}" || text == "[]")
}

// checkProse applies the input rule that goes with format:"markdown" to the
// columns about to be written. A nil only means every one of them, which is
// the insert case; Update passes the columns that actually moved, so an
// unrelated edit is never refused for something already in the row.
//
// It lives beside the permission checks rather than in each command because
// that is the same argument the field kinds settled: a rule stated once and
// enforced on the only path to the database cannot be forgotten at a call
// site, and both the CLI and the MCP server arrive here.
func checkProse(r Record, fields []field, only map[string]bool) error {
	for _, f := range fields {
		if f.format != formatMarkdown || (only != nil && !only[f.column]) {
			continue
		}
		text, err := renderValue(f.value(r))
		if err != nil {
			return fmt.Errorf("%s.%s: %w", r.table(), f.column, err)
		}
		if err := markdown.Validate(text); err != nil {
			return fmt.Errorf("%s.%s: %w", r.table(), f.column, err)
		}
	}
	return nil
}

func changedColumns(changes []Change) map[string]bool {
	columns := make(map[string]bool, len(changes))
	for _, change := range changes {
		columns[change.Column] = true
	}
	return columns
}

func (t *Tx) checkPermission(r Record, changes []Change) error {
	allowed := t.actor.writes()
	for _, change := range changes {
		if change.Kind != allowed {
			return fmt.Errorf("%s may not write %s.%s: it is %s, and %s writes only %s fields",
				t.actor, r.table(), change.Column, change.Kind, t.actor, allowed)
		}
	}
	return nil
}

// assignments builds the SET clause: every changed column, plus the auto
// columns that go with any write.
func (t *Tx) assignments(r Record, fields []field, changes []Change) ([]string, []any) {
	changed := changedColumns(changes)

	var assignments []string
	var args []any
	for _, f := range fields {
		if !changed[f.column] && f.kind != Auto {
			continue
		}
		assignments = append(assignments, f.column+" = ?")
		args = append(args, f.value(r))
	}
	return assignments, args
}

// stamp sets the given kinds of column to the transaction's timestamp, in the
// caller's struct as well as in the database, so the value they hold
// afterwards matches what was written.
func (t *Tx) stamp(r Record, fields []field, kinds ...FieldKind) {
	wanted := make(map[FieldKind]bool, len(kinds))
	for _, k := range kinds {
		wanted[k] = true
	}
	for _, f := range fields {
		if wanted[f.kind] {
			t.setTimestamp(r, f)
		}
	}
}

// stampNew stamps a record being inserted.
//
// It differs from stamp in one way: a nullable auto column is left NULL.
// Nullability is how such a column says "this has not happened yet" —
// pr.last_synced_at on a pull request nobody has synced — and stamping it at
// insert would claim something that is not true.
func (t *Tx) stampNew(r Record, fields []field) {
	for _, f := range fields {
		switch {
		case f.kind == Created:
			t.setTimestamp(r, f)
		case f.kind == Auto && !isNullable(r, f):
			t.setTimestamp(r, f)
		}
	}
}

// setTimestamp writes the transaction's time into a column, whether it is a
// plain string or a nullable one. Anything else is left alone: a timestamp
// column is text in this schema, and silently doing nothing to an unexpected
// type is better than guessing at it.
func (t *Tx) setTimestamp(r Record, f field) {
	target := reflect.ValueOf(r).Elem().Field(f.index)
	switch target.Interface().(type) {
	case string:
		target.SetString(t.at)
	case sql.NullString:
		target.Set(reflect.ValueOf(sql.NullString{String: t.at, Valid: true}))
	}
}

func isNullable(r Record, f field) bool {
	_, nullable := reflect.ValueOf(r).Elem().Field(f.index).Interface().(sql.NullString)
	return nullable
}
